meta_product_name: "David Clim"
meta_title: "David Clim – Expert en Climatisation à Fréjus et Saint-Raphaël"
meta_description: "Installation, dépannage et entretien de climatisations à Fréjus, Saint-Raphaël et alentours. Intervention rapide pour particuliers et professionnels."
meta_image: "air-conditioner-og.png" # doit être présent dans app/assets/images/
twitter_account: "" # optionnel, laisse vide si pas de compte

# twitter_account: “@product_twitter_account” # required for Twitter Cards
