
meta_product_name: "David Clim"

meta_title: "David Clim - Votre Expert en Climatisation"

meta_description: "David Clim : Votre spécialiste climatisation à Fréjus et Saint-Raphaël. Installation, entretien, dépannage pour particuliers et professionnels. Contactez-nous pour concrétiser votre projet et profiter d'un confort optimal toute l'année !"

meta_image: "air-conditioner-1.png" # should exist in `app/assets/images/`

# twitter_account: “@product_twitter_account” # required for Twitter Cards
