
meta_product_name: "David Clim"

meta_title: "David Clim - Votre Expert en Climatisation"

meta_description: "David Clim : Votre partenaire climatisation à Fréjus, Saint-Raphaël et environs. Services complets pour particuliers et professionnels : installation, entretien, nettoyage, dépannage. Contactez-nous pour concrétiser votre projet."

meta_image: "air-conditioner-1.png" # should exist in `app/assets/images/`

# twitter_account: "@masabe07" # required for Twitter Cards
